# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uifontfile_format.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uifontfile_format.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('H\001\200\001\000'),
  serialized_pb=_b('\n\x17uifontfile_format.proto\"C\n\rCUIFontFilePB\x12\x16\n\x0e\x66ont_file_name\x18\x01 \x01(\t\x12\x1a\n\x12opentype_font_data\x18\x02 \x01(\x0c\"\xb1\x01\n\x14\x43UIFontFilePackagePB\x12\x17\n\x0fpackage_version\x18\x01 \x02(\r\x12J\n\x14\x65ncrypted_font_files\x18\x02 \x03(\x0b\x32,.CUIFontFilePackagePB.CUIEncryptedFontFilePB\x1a\x34\n\x16\x43UIEncryptedFontFilePB\x12\x1a\n\x12\x65ncrypted_contents\x18\x01 \x01(\x0c\x42\x05H\x01\x80\x01\x00')
)




_CUIFONTFILEPB = _descriptor.Descriptor(
  name='CUIFontFilePB',
  full_name='CUIFontFilePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='font_file_name', full_name='CUIFontFilePB.font_file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opentype_font_data', full_name='CUIFontFilePB.opentype_font_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=94,
)


_CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB = _descriptor.Descriptor(
  name='CUIEncryptedFontFilePB',
  full_name='CUIFontFilePackagePB.CUIEncryptedFontFilePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_contents', full_name='CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=274,
)

_CUIFONTFILEPACKAGEPB = _descriptor.Descriptor(
  name='CUIFontFilePackagePB',
  full_name='CUIFontFilePackagePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_version', full_name='CUIFontFilePackagePB.package_version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encrypted_font_files', full_name='CUIFontFilePackagePB.encrypted_font_files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=274,
)

_CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB.containing_type = _CUIFONTFILEPACKAGEPB
_CUIFONTFILEPACKAGEPB.fields_by_name['encrypted_font_files'].message_type = _CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB
DESCRIPTOR.message_types_by_name['CUIFontFilePB'] = _CUIFONTFILEPB
DESCRIPTOR.message_types_by_name['CUIFontFilePackagePB'] = _CUIFONTFILEPACKAGEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CUIFontFilePB = _reflection.GeneratedProtocolMessageType('CUIFontFilePB', (_message.Message,), dict(
  DESCRIPTOR = _CUIFONTFILEPB,
  __module__ = 'uifontfile_format_pb2'
  # @@protoc_insertion_point(class_scope:CUIFontFilePB)
  ))
_sym_db.RegisterMessage(CUIFontFilePB)

CUIFontFilePackagePB = _reflection.GeneratedProtocolMessageType('CUIFontFilePackagePB', (_message.Message,), dict(

  CUIEncryptedFontFilePB = _reflection.GeneratedProtocolMessageType('CUIEncryptedFontFilePB', (_message.Message,), dict(
    DESCRIPTOR = _CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB,
    __module__ = 'uifontfile_format_pb2'
    # @@protoc_insertion_point(class_scope:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
    ))
  ,
  DESCRIPTOR = _CUIFONTFILEPACKAGEPB,
  __module__ = 'uifontfile_format_pb2'
  # @@protoc_insertion_point(class_scope:CUIFontFilePackagePB)
  ))
_sym_db.RegisterMessage(CUIFontFilePackagePB)
_sym_db.RegisterMessage(CUIFontFilePackagePB.CUIEncryptedFontFilePB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
